# docs: https://github.com/joomla-docker/docker-joomla
# image: https://hub.docker.com/r/websoft9dev/discuz

version: '3.8'

services:
  discuz:
    image: websoft9dev/discuz:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - '${APP_PORT}:80'
    environment:
      - DISCUZ_DB_HOST=mysql
      - DISCUZ_DB_USER=$DB_MYSQL_USER
      - DISCUZ_DB_DATABASE=$DB_MYSQL_NAME
      - DISCUZ_DB_PASSWORD=$DB_MYSQL_PASSWORD
    volumes:
      - 'discuz:/var/www/html'
    depends_on:
      - db

  db:
    image: mysql:$DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    restart: always

networks:
  default:
      name: $APP_NAME

volumes:
  mysql:
  discuz:
